-- SUPER-BOT 
 --ESTE ES UN BOT GENERADO PARA ENVIAR LAS ESTADISTICAS DE LA COBRANZA APLICADA EN SIRCA
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE 
	@ID										AS	INTEGER,
	@TOTALARQUEO							AS	INTEGER,
	@TOTALRSOK								AS	INTEGER,
	@TOTAL									AS	INTEGER,
	@TABLEHTML								NVARCHAR(MAX),
	@MENSAJE								NVARCHAR(MAX),
	@SOLICITUDESPORSTATUS					NVARCHAR(MAX),
	@SOLICITUDESPENDIENTESPORREGION			NVARCHAR(MAX),
	@SOLICITUDESPENDIENTES					INT,
	@SUBJECT								AS VARCHAR(50),
	@DESTINATARIOSRESUMEN					AS VARCHAR(500),
	@DESTINATARIOSDETALLE					AS VARCHAR(500),
	@ARCHIVO								AS VARCHAR(500)

	SET @DESTINATARIOSRESUMEN = 'GERARDO.BAUTISTA@CFE.GOB.MX;LUIS.RODRIGUEZ22@CFE.GOB.MX; CLAUDIA.MEZA@CFE.GOB.MX ; ALEJANDROMURO@CFE.GOB.MX; ALVARO.MARTINEZ@CFE.GOB.MX; CARLOS.MEDINA@CFE.GOB.MX'
	SET @DESTINATARIOSDETALLE = 'GERARDO.BAUTISTA@CFE.GOB.MX;LUIS.RODRIGUEZ22@CFE.GOB.MX; CLAUDIA.MEZA@CFE.GOB.MX'
	--SET @DESTINATARIOSDETALLE = 'LUIS.RODRIGUEZ22@CFE.GOB.MX'
	--SET @DESTINATARIOSRESUMEN = 'LUIS.RODRIGUEZ22@CFE.GOB.MX'
	
	-- OBTENGO ID A PROCESAR
	
	--SET @ID = 61
	  
	SELECT  TOP 1 @ID=ID, @ARCHIVO=ARCHIVO
	FROM [SOF_SIRCANAC].[DBO].[CONTROL_ARQUEO]
	WHERE FECHAPROCESOCARGA IS NULL


	SELECT @TOTAL=isnull(COUNT(*),0)
	FROM [SOF_SIRCANAC].[DBO].[CONTROL_ARQUEO]
	WHERE ID=@ID
	

	IF(@TOTAL > 0) BEGIN
  -- OBTENGO TODOS LOS PAGOS QUE CORRESPONDEN A ESTE LOTE
  
		SELECT @TOTALARQUEO=COUNT(*)
		FROM [SOF_SIRCANAC].[HISTORICO].[ARQUEO]
		WHERE IDCTRLARQUEO = @ID AND PROCESADO= 1 
		 
		--OBTENGO SI YA TODOS LOS PAGOS FUERON PROCESADOS POR EL STORED DE ARQUEO 

		SELECT   
		@TOTALRSOK = COUNT(DISTINCT IDCARGADIARIAFECHA) 
		FROM [SOF_SIRCANAC].[HISTORICO].[ARQUEO] A
		JOIN SIRCANAC.DBO.CARGADIARIAFECHA C ON C.IDARQUEO=A.IDARQUEO
		LEFT JOIN SIRCANAC.DBO.REGISTROSSICOMOK R ON R.IDCARGADIARIAFECHA=C.ID
		LEFT JOIN SIRCANAC.DBO.CATALOGO_ERRORES CAT ON CAT.ERROR=R.ERROR
		WHERE IDCTRLARQUEO = @ID AND R.PROCESADO = 1 


		-- SI TODO ESTA PROCESADO OBTENGO LOS DATOS 
		IF (@TOTALARQUEO=@TOTALRSOK) BEGIN
		
			-- ENVIO RESUMEN COBRANZA
			EXEC SOF_SircaNac.dbo.superBot_envioResumenCobranza @ID, @TOTALARQUEO, @ARCHIVO
			
			--ENVIO ARCHIVOS DE DETALLES
			EXEC SOF_SircaNac.dbo.superBot_envioDetalleCobranza @ID, @DESTINATARIOSRESUMEN
			EXEC SOF_SircaNac.dbo.superBot_envioDetalleCobranzaRSOK @ID, @DESTINATARIOSDETALLE
			-- SE UPDATEA [SOF_SIRCANAC].[DBO].[CONTROL_ARQUEO]			
			
			UPDATE [SOF_SIRCANAC].[DBO].[CONTROL_ARQUEO]
			SET FECHAPROCESOCARGA = GETDATE()
			WHERE ID=@ID


		END

	END
	
	    




