DECLARE 
@NUMCREDITO AS VARCHAR(9),
@CONTADOR	AS INT	

SET @CONTADOR = 1

INSERT INTO [SIRCANAC].[DBO].[TMPCREDSMOTIVOFALTAID]
           ([RPU]
           ,[SOLICITUDSCC]
           ,[PAGARE]
           ,[AÑOMES]
           ,[FECHA]
           ,[IDREGISTROSICOM]
           ,[IMPORTE]
           ,[APPOPFIN])
SELECT 
  D.RPU,
  D.SOLICITUDSCC,
  D.PAGARE,
  AÑOMES = CONVERT(VARCHAR(6),D.FECHA,112),
  D.FECHA,
  D.IDREGISTROSICOM,
  IMPORTE = (D.IMPORTEOPFIN + D.INTERESOPFIN + D.IVAOPFIN)
  ,D.APPOPFIN
 FROM DBO.DET_AMORTIZACION D WITH(NOLOCK)
 INNER JOIN DBO.CREDITOS C ON C.NUMCREDITO = D.SOLICITUDSCC AND C.TIPOCREDITO IN ('PA','CV')
 LEFT JOIN TMPCREDSMOTIVOFALTAID TMP ON TMP.RPU=D.RPU AND TMP.SOLICITUDSCC=D.SOLICITUDSCC 
 AND TMP.PAGARE=D.PAGARE AND TMP.AÑOMES=CONVERT(VARCHAR(6),D.FECHA,112) AND TMP.FECHA=D.FECHA      
 WHERE ISNULL(D.IDREGISTROSICOM,0) = 0
 AND D.ESTATUS = 14 AND TMP.SOLICITUDSCC IS NULL
  
SELECT TOP 1 @NUMCREDITO=SOLICITUDSCC
FROM DBO.TMPCREDSMOTIVOFALTAID
WHERE PROCESADO IS NULL
PRINT @NUMCREDITO

WHILE @NUMCREDITO IS NOT NULL --AND @CONTADOR < 100
BEGIN
	EXEC SPADDIDREGISTROSSICOMOKTODET_AMORTIZACION @NUMCREDITO
	
	UPDATE DBO.TMPCREDSMOTIVOFALTAID
	SET PROCESADO=1
	WHERE SOLICITUDSCC=@NUMCREDITO
	
	SELECT TOP 1 @NUMCREDITO=SOLICITUDSCC
	FROM DBO.TMPCREDSMOTIVOFALTAID
	WHERE PROCESADO IS NULL
	PRINT 'PROCESANDO :' + @NUMCREDITO

	--SET @CONTADOR = @CONTADOR + 1
END




