

select sum(CANTIDADENREGISTROSSICOMOK- IMPORTERSOKINICIAL)
from LOGSPAPLICARARQUEO
where FECHAEJECUCION >= '20170301'


sp_helptext COMPARATIVO_TABLAS_RESUMEN

CREATE PROCEDURE LLENARCOMPARATIVO_TABLAPAGOS  
AS  
BEGIN  
DECLARE   
  @FECHAINICIAL AS DATE,   
  @FECHAAUX  AS DATE  
SET @FECHAINICIAL='20160201'  
  
SELECT @FECHAAUX=CONVERT(DATE,DATEADD(DD,1,MAX(FECHAPROCESO)))  
FROM COMPARATIVO_TABLAPAGOS  
  
IF @FECHAAUX<CONVERT(DATE,GETDATE()) AND  @FECHAAUX > @FECHAINICIAL  
BEGIN   
 WHILE @FECHAAUX<CONVERT(DATE,GETDATE())  
 BEGIN   
  EXEC SIRCANAC.DBO.[COMPARATIVO_TABLAS_RESUMEN] @FECHAAUX  
  PRINT 'INSERTANDO '  
  PRINT @FECHAAUX  
  SET @FECHAAUX=DATEADD(DD,1,@FECHAAUX)  
 END   
END   
END  



-- =============================================  
-- AUTHOR:  <AUTHOR,,NAME>  
-- CREATE DATE: <CREATE DATE,,>  
-- DESCRIPTION: <DESCRIPTION,,>  
  
CREATE PROCEDURE [dbo].[Comparativo_tablas_Resumen]   
@FECHAPROCESO DATETIME  
  
AS BEGIN                                                
DECLARE   
@NUMERO_PAGOS_POR_RAP  AS INT  
,@NUMERO_PAGOSPORARCHIVO AS INT  
,@IMPORTE_PAGOSPORRAP  AS FLOAT  
,@IMPORTEPAGOSPORARCHIVO AS FLOAT  
,@PROGRAMA     AS VARCHAR(50)  
,@FECHA      AS DATE   
  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED   
SELECT @FECHA=CONVERT(DATE,FECHAPROCESO)  
FROM [SIRCANAC].[DBO].[COBRANZADIARIASIRCA]  
WHERE FECHAPROCESO=CONVERT(DATE,@FECHAPROCESO)  
IF @FECHA IS NULL AND CONVERT(DATE,@FECHAPROCESO) < CONVERT(DATE,GETDATE())  
BEGIN   
 PRINT 'INSERTANDO DATOS DE LA FECHA '  
 PRINT @FECHAPROCESO  
   
 INSERT INTO [SIRCANAC].[DBO].[COMPARATIVO_TABLAPAGOS]  
           ([FECHAPROCESO]  
           ,[NUMERO_PAGOS_POR_RAP]  
           ,[IMPORTE_PAGOSPORRAP]  
           ,[NUMERO_PAGOSPORARCHIVO]  
           ,[IMPORTEPAGOSPORARCHIVO]  
           ,[PROGRAMA]  
           ,[PAGOS_RAP_DET_AMORTIZACION]  
           ,[CANTIDAD_PAGOS_RAP_DET_AMORTIZACION]  
           ,[PAGOS_ARCHIVOS_DET_AMORTIZACION]  
           ,[CANTIDADPAGOS_ARCHIVOS_DET_AMORTIZACION])  
 SELECT   
 CONVERT(DATE,FECHAPROCESO)  
 ,isnull(SUM(CASE WHEN ARCHIVO = 'CUENTARAP' THEN 1 ELSE 0 END),0) "NUMERO PAGOS POR RAP "   
 ,isnull(SUM(CASE WHEN ARCHIVO = 'CUENTARAP' THEN IMPORTE ELSE 0 END),0) "MONTO POR RAP "   
 ,isnull(SUM(CASE WHEN ARCHIVO <> 'CUENTARAP' THEN 1 ELSE 0 END),0) "NUMERO PAGOS POR ARCHIVO "   
 ,isnull(SUM(CASE WHEN ARCHIVO <> 'CUENTARAP' THEN IMPORTE ELSE 0 END),0) "MONTO POR ARCHIVO "   
 ,CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  END AS PROGR
AMA   
 ,isnull(TMP.PAGOS_RAP,0)  
 ,isnull(TMP.MONTO_PAGOS_RAP,0)  
 ,isnull(TMP.PAGOS_ARCHIVOS,0)  
 ,isnull(TMP.MONTO_PAGOS_ARCHIVOS,0)  
 FROM  REGISTROSSICOMOK R   
 JOIN CREDITOS C ON C.NUMCREDITO=R.NUMCREDITO  
 left JOIN   
 (  
 SELECT   
 CONVERT(DATE,FECHAOPFIN) AS FECHAPAGOMAX  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 1 ELSE 0 END ) AS PAGOS_RAP  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN SALDOOPFIN ELSE 0 END ) AS MONTO_PAGOS_RAP  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE 1 END ) AS PAGOS_ARCHIVOS  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE SALDOOPFIN END ) AS MONTO_PAGOS_ARCHIVOS  
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  AS TIPO  
 FROM DET_AMORTIZACION D  
 JOIN CREDITOS CTMP ON CTMP.NUMCREDITO=D.SOLICITUDSCC  
 WHERE CONVERT(DATE,FECHAOPFIN) = @FECHAPROCESO AND ESTATUSOPFIN = 1  
 GROUP BY CONVERT(DATE,FECHAOPFIN)  
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  
 ) AS TMP ON TMP.FECHAPAGOMAX=CONVERT(DATE,R.FECHAPROCESO)   
 AND TMP.TIPO= CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END 
 END   
 WHERE CONVERT(DATE,FECHAPROCESO) = @FECHAPROCESO AND ERROR=0  
 GROUP BY CONVERT(DATE,FECHAPROCESO)  
 , CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  END   
 ,TMP.PAGOS_RAP  
 ,TMP.MONTO_PAGOS_RAP  
 ,TMP.PAGOS_ARCHIVOS  
 ,TMP.MONTO_PAGOS_ARCHIVOS  
 /*  
 QUERYS ORIGINALES  
 SELECT   
 CONVERT(DATE,FECHAPROCESO)  
 ,SUM(CASE WHEN ARCHIVO = 'CUENTARAP' THEN 1 ELSE 0 END) "NUMERO PAGOS POR RAP "   
 ,SUM(CASE WHEN ARCHIVO = 'CUENTARAP' THEN IMPORTE ELSE 0 END) "MONTO POR RAP "   
 ,SUM(CASE WHEN ARCHIVO <> 'CUENTARAP' THEN 1 ELSE 0 END) "NUMERO PAGOS POR ARCHIVO "   
 ,SUM(CASE WHEN ARCHIVO <> 'CUENTARAP' THEN IMPORTE ELSE 0 END) "MONTO POR ARCHIVO "   
 ,CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  END AS PROGR
AMA   
 FROM  REGISTROSSICOMOK R   
 JOIN CREDITOS C ON C.NUMCREDITO=R.NUMCREDITO  
 WHERE CONVERT(DATE,FECHAPROCESO) = '20160303' AND ERROR=0  
 GROUP BY CONVERT(DATE,FECHAPROCESO), CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE
 'NINGUNO' END END END  END   
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED   
 SELECT   
 CONVERT(DATE,FECHAOPFIN) AS FECHAPAGOMAX  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 1 ELSE 0 END ) AS PAGOS_RAP  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN SALDOOPFIN ELSE 0 END ) AS MONTO_PAGOS_RAP  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE 1 END ) AS PAGOS_ARCHIVOS  
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE SALDOOPFIN END ) AS MONTO_PAGOS_ARCHIVOS  
 ,CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  END AS PROGR
AMA   
 FROM DET_AMORTIZACION D  
 JOIN CREDITOS C ON C.NUMCREDITO=D.SOLICITUDSCC  
 WHERE CONVERT(DATE,FECHAOPFIN) = '20160303' AND ESTATUSOPFIN = 1  
 GROUP BY CONVERT(DATE,FECHAOPFIN), CASE WHEN C.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN C.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN C.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN C.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE '
NINGUNO' END END END  END   
 */  
   
 ;with tablasac AS (  
 SELECT     
 CONVERT(DATE,FECHAOPFIN) AS FECHAPAGOMAX    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 1 ELSE 0 END ) AS PAGOS_RAP    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN SALDOOPFIN ELSE 0 END ) AS MONTO_PAGOS_RAP    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE 1 END ) AS PAGOS_ARCHIVOS    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE d.pagodec END ) AS MONTO_PAGOS_ARCHIVOS    
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  AS TIPO    
 FROM DET_AMORTIZACION D    
 JOIN CREDITOS CTMP ON CTMP.NUMCREDITO=D.SOLICITUDSCC    
 WHERE ESTATUSOPFIN = 1   and CONVERT(DATE,FECHAOPFIN) =@FECHAPROCESO -- >= '20160501' and CONVERT(DATE,FECHAOPFIN) <  '20160603'  AND ESTATUSOPFIN = 1    
 GROUP BY CONVERT(DATE,FECHAOPFIN)    
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  
 )  
  
 INSERT INTO [SircaNac].[dbo].[Comparativo_TablaPagos]  
         ([FechaProceso]  
      ,[numero_pagos_por_RAP]  
            ,[numero_pagosporArchivo]  
         ,[Importe_pagosporRAP]  
      ,[ImportePagosporArchivo]  
            ,[Programa]  
         ,[pagos_rap_det_amortizacion]  
      ,[pagos_archivos_det_amortizacion]  
            ,[cantidad_pagos_rap_det_amortizacion]  
         ,[cantidadpagos_archivos_det_amortizacion])  
 select s.FECHAPAGOMAX,'0','0','0','0',s.TIPO , s.PAGOS_RAP, s.PAGOS_ARCHIVOS, s.MONTO_PAGOS_RAP,s.MONTO_PAGOS_ARCHIVOS  
 from tablasac s   
 left join [SIRCANAC].[DBO].[COMPARATIVO_TABLAPAGOS] c on c.programa=s.TIPO and c.FechaProceso=@FECHAPROCESO  
 where c.programa is null  
  
  
 update  [SIRCANAC].[DBO].[COMPARATIVO_TABLAPAGOS]   
 set pagos_rap_det_amortizacion=0 , pagos_archivos_det_amortizacion=0  
 , cantidad_pagos_rap_det_amortizacion=0, cantidadpagos_archivos_det_amortizacion=0  
 where FechaProceso=@FECHAPROCESO  
  
  
 ;with tablasac AS (  
 SELECT     
 CONVERT(DATE,FECHAOPFIN) AS FECHAPAGOMAX    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 1 ELSE 0 END ) AS PAGOS_RAP    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN SALDOOPFIN ELSE 0 END ) AS MONTO_PAGOS_RAP    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE 1 END ) AS PAGOS_ARCHIVOS    
 ,SUM(CASE WHEN RAPOPFIN=1 THEN 0 ELSE d.pagodec END ) AS MONTO_PAGOS_ARCHIVOS    
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  AS TIPO    
 FROM DET_AMORTIZACION D    
 JOIN CREDITOS CTMP ON CTMP.NUMCREDITO=D.SOLICITUDSCC    
 WHERE ESTATUSOPFIN = 1   and CONVERT(DATE,FECHAOPFIN) =@FECHAPROCESO -- >= '20160501' and CONVERT(DATE,FECHAOPFIN) <  '20160603'  AND ESTATUSOPFIN = 1    
 GROUP BY CONVERT(DATE,FECHAOPFIN)    
 ,CASE WHEN CTMP.TIPOCREDITO IN ('RF','AA') THEN 'SENER' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('PA')THEN 'PAEEEM' ELSE CASE WHEN CTMP.TIPOCREDITO IN ('MT') THEN 'MI TORTILLA 'ELSE CASE WHEN CTMP.TIPOCREDITO IN ('LD') THEN 'LEDS' ELSE 'NINGUNO' END END END  
END  
 )  
  
  
 update  c  
 set c.pagos_rap_det_amortizacion=s.PAGOS_RAP , c.pagos_archivos_det_amortizacion=s.PAGOS_ARCHIVOS  
 , c.cantidad_pagos_rap_det_amortizacion=s.MONTO_PAGOS_RAP, c.cantidadpagos_archivos_det_amortizacion=s.MONTO_PAGOS_ARCHIVOS  
 from [SIRCANAC].[DBO].[COMPARATIVO_TABLAPAGOS] c  
 join tablasac s on s.tipo=c.programa and c.FechaProceso=s.FECHAPAGOMAX  
 where c.FechaProceso=@FECHAPROCESO   
END   
ELSE   
BEGIN  
 PRINT 'NO SE INSERTARON DATOS POR QUE YA EXISTEN DATOS O LA FECHA NO ES VALIDA'  
END  
END  
  
  
  
  
  
  
  
  