
-- STORED PROCEDURE : SPPASARPAGOSCIERREMENSUAL

DECLARE
		@ANIOACTUAL			AS INT,
		@MESACTUAL			AS VARCHAR(2),
		@FECHAINICIAL		AS VARCHAR(8),
		@FECHAFINAL			AS VARCHAR(8),
		@MESANTERIOR		AS VARCHAR(2),
		@CANTIDADPAGOS		AS INT,
		@MENSAJE			AS VARCHAR(500),
		@DIASINTERVALO		AS INT,
		@SUBJECT			AS VARCHAR(50),
		@DESTINATARIOS		AS VARCHAR(500)

SET @DESTINATARIOS = 'LUIS.RODRIGUEZ22@CFE.GOB.MX, JORGE.RODRIGUEZ17@CFE.GOB.MX, ALEJANDRO.MURO@CFE.GOB.MX '
SET @MENSAJE = ''
SET @SUBJECT = ''

--OBTENGO EL PRIMER DIA DEL MES 

SELECT @MESACTUAL=RIGHT('00' +CONVERT(VARCHAR,MONTH(GETDATE())), 2), @ANIOACTUAL=YEAR(GETDATE())
SELECT @FECHAFINAL=CONVERT(VARCHAR,@ANIOACTUAL)+CONVERT(VARCHAR,RIGHT('00' + @MESACTUAL,2)) + '01'
PRINT 'FECHA DE INICIO DE MES'
PRINT @FECHAFINAL
-- FECHA DE CORTE ANTERIOR 
--OBTENGO MES ANTERIOR 
SELECT @MESANTERIOR=RIGHT('00' +CONVERT(VARCHAR,MONTH(DATEADD(MM, -1,GETDATE()))), 2)
PRINT @MESANTERIOR
SELECT @FECHAINICIAL=CONVERT(VARCHAR,FECHAINICIO,112) 
FROM FECHACORTEFIDE 
WHERE YEAR(FECHAINICIO) = @ANIOACTUAL AND RIGHT('00'+CONVERT(VARCHAR,MONTH(FECHAINICIO)),2) = @MESANTERIOR
PRINT @FECHAINICIAL


set transaction isolation level read uncommitted 
SELECT @CANTIDADPAGOS=COUNT(*) 
FROM PAGOS P
WHERE P.FINSERT  > @FECHAINICIAL AND P.FINSERT < @FECHAFINAL


-- OBTENGO DIAS DENTRO DEL PERIODO PARA VALIDAR 

select @DIASINTERVALO = DATEDIFF(dd, @FECHAINICIAL,@FECHAFINAL)


-- VERIFICO SEA UNA CANTIDAD VALIDA DE PAGOS
IF @CANTIDADPAGOS > 0 AND @CANTIDADPAGOS < 4000 AND @DIASINTERVALO > 0 AND @DIASINTERVALO < 10 AND @FECHAINICIAL IS NOT NULL AND @FECHAFINAL IS NOT NULL 
BEGIN
	set transaction isolation level read uncommitted 
	SELECT dateadd(hh,1,convert(datetime,@FECHAFINAL)) as fecha_destino  , P.FINSERT,* 
	FROM PAGOS P
	WHERE P.FINSERT  > @FECHAINICIAL AND P.FINSERT < @FECHAFINAL
	ORDER BY P.FINSERT DESC
	/*
	UPDATE PAGOS 
	SET FINSERT = dateadd(hh,1,convert(datetime,@FECHAFINAL))
	WHERE P.FINSERT  > @FECHAINICIAL AND P.FINSERT < @FECHAFINAL
	*/
	SET @SUBJECT = '[CORRECTO] EJECUCIÓN CORRECTA DEL STORED SPPASARPAGOSCIERREMENSUAL'
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL DE FORMA CORRECTA <BR />
					SE PROCESARON  ' + CONVERT(VARCHAR,@CANTIDADPAGOS) + 'PAGOS' + 
					'<BR /> SE PASARON LOS PAGOS DEL ' +CONVERT(VARCHAR, @FECHAINICIAL, 112 ) + ' AL '+ CONVERT(VARCHAR,@FECHAFINAL ,112) 
					+ '<BR /> SE PASARON AL ' + CONVERT(VARCHAR,DATEADD(HH,1,CONVERT(DATETIME,@FECHAFINAL)),112)
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
END
ELSE
BEGIN 
	SET @SUBJECT = '[ERROR] EJECUCIÓN INCORRECTA DEL STORED SPPASARPAGOSCIERREMENSUAL'
	IF  @CANTIDADPAGOS < 0 
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					LA CANTIDAD DE PAGOS ES MENOS A CERO ' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 
	IF  @CANTIDADPAGOS > 4000
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					LA CANTIDAD DE PAGOS ES MAYOR A 4000 SE RECOMIENDA UNA REVISION MANUAL ' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 
	IF  @DIASINTERVALO < 0 
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					LOS DIAS DEL INTERVALO DE FECHAS QUEDARON NEGATIVOS POR LO QUE SE RECOMIENDA UNA REVISION MANUAL' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 
	IF  @DIASINTERVALO > 10 
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					LOS DIAS DEL INTERVALO DE FECHAS FUE MAYOR A 10 DIAS POR LO QUE SE RECOMIENDA UNA REVISION MANUAL' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 
	IF  @FECHAINICIAL IS NULL
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					NO SE ENCONTRO FECHA EN LA TABLA FECHACORTEFIDE CORRESPONDIENTE A ESTE PERIODO POR LO QUE SE RECOMIENDA UNA REVISION MANUAL ' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 
	IF  @FECHAFINAL IS NULL
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					NO SE ENCONTRO FECHA FINAL POR LO QUE SE RECOMIENDA UNA REVISION MANUAL ' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 	
	IF  @CANTIDADPAGOS = 0 
	BEGIN
	SET @MENSAJE = 'SE HA EJECUTADO EL PROCESO SPPASARPAGOSCIERREMENSUAL Y HA DETECTADO UN ERROR <BR />
					NO SE HAN ENCONTRADO PAGOS A PROCESAR ' 
					+ '<BR /> QUE TENGA UN  BUEN DIA  ' 
	END 			
END
-- ENVIAMOS EMAIL DE AVISO DE EJECUCIÓN

PRINT @MENSAJE

USE msdb;
EXEC sp_send_dbmail @profile_name='sql1',
@recipients=@DESTINATARIOS,
@subject=@SUBJECT,
@body=@MENSAJE,
@body_format = 'HTML' ;








