DECLARE 
@NUMCREDITO AS VARCHAR(9),
@RPU		AS	VARCHAR(12),
@CANTIDADREGISTROSSICOMOK AS MONEY,
@CANTIDADPAGOS AS MONEY,
@id as int

set @NUMCREDITO=NULL

SELECT TOP 1 @NUMCREDITO=L.NUMCREDITO
FROM LOGSPAPLICARARQUEO L
WHERE USUARIO= 'AMURO' AND FECHAEJECUCION > '2017-02-24 16:40:33.993'
AND CANTIDADPAGADAENARQUEO=CANTIDADENREGISTROSSICOMOK AND (SELECT SUM(IMPORTE) FROM PAGOS WHERE NUMCREDITO=L.NUMCREDITO) > CANTIDADENREGISTROSSICOMOK

WHILE @NUMCREDITO IS NOT NULL 
BEGIN 

	PRINT 'PROCESANDO '+@NUMCREDITO
	
	SELECT @CANTIDADPAGOS=SUM(IMPORTE), @RPU=RPU
	FROM PAGOS 
	WHERE NUMCREDITO=@NUMCREDITO
	GROUP BY RPU
	
	SELECT @CANTIDADREGISTROSSICOMOK=SUM(IMPORTE) 
	FROM REGISTROSSICOMOK RS WITH(NOLOCK) 	
	WHERE NUMCREDITO=@NUMCREDITO
	AND ISNULL(RS.ARCHIVO ,'') NOT IN ('CUENTARAP','PAGORAP','LIQUIDACIÓN EN VENTANILLA CFE (PAGO FUERA DE FACTURACIÓN)','NA - EXTRACTOR1','NA - EXTRACTOR2','NA - ARQUEO1','NA - ARQUEO2')
	AND RS.ESTATUS = '01'
	AND RS.ERROR = 0
	AND RS.PROCESADO = 1 
	--AND ISNULL(RS.PAGODEMAS,0) <> 1
	AND ISNULL(RS.PAGOELIMINADO,0) <> 1


	PRINT 'CANTIDAD EN PAGOS '+CONVERT(VARCHAR,@CANTIDADPAGOS)
	PRINT 'CANTIDAD EN REGISTROSSICOMOK '+CONVERT(VARCHAR,@CANTIDADREGISTROSSICOMOK)

	set @ID =NULL

	IF @CANTIDADPAGOS > @CANTIDADREGISTROSSICOMOK
	BEGIN
	
			SELECT TOP 1  @ID=ID 
			FROM PAGOS 
			WHERE NUMCREDITO=@NUMCREDITO AND APLICACIONSQL =  'SPAPLICARARQUEO' AND IMPORTE <= @CANTIDADPAGOS - @CANTIDADREGISTROSSICOMOK
			ORDER BY IMPORTE, FINSERT  DESC
		
			IF @id IS NULL AND @CANTIDADPAGOS > @CANTIDADREGISTROSSICOMOK
			BEGIN
				SELECT TOP 1  @ID=ID 
				FROM PAGOS 
				WHERE NUMCREDITO=@NUMCREDITO AND APLICACIONSQL =  'SPAPLICARARQUEO' 
				ORDER BY FINSERT  DESC
			END
			BEGIN TRANSACTION
		WHILE @CANTIDADPAGOS > @CANTIDADREGISTROSSICOMOK AND @ID IS NOT NULL
		BEGIN
		
	
			DELETE FROM PAGOS WHERE ID=@ID AND NUMCREDITO=@NUMCREDITO
		
			PRINT 'ELIMINADO PAGO '+CONVERT(VARCHAR, @ID)

			set @ID =NULL
		
			SELECT @CANTIDADPAGOS=SUM(IMPORTE)
			FROM PAGOS 
			WHERE NUMCREDITO=@NUMCREDITO
		
			SELECT TOP 1  @ID=ID 
			FROM PAGOS 
			WHERE NUMCREDITO=@NUMCREDITO AND APLICACIONSQL =  'SPAPLICARARQUEO' AND IMPORTE <= @CANTIDADPAGOS - @CANTIDADREGISTROSSICOMOK
			ORDER BY IMPORTE, FINSERT  DESC		
			IF @id IS NULL AND @CANTIDADPAGOS > @CANTIDADREGISTROSSICOMOK
			BEGIN
				SELECT TOP 1  @ID=ID 
				FROM PAGOS 
				WHERE NUMCREDITO=@NUMCREDITO AND APLICACIONSQL =  'SPAPLICARARQUEO' 
				ORDER BY FINSERT  DESC
			END		
		END
		COMMIT
		COMMIT
	END 
	exec dbo.FIDEArreglaPagos @NUMCREDITO


	SELECT @CANTIDADPAGOS=SUM(IMPORTE), @RPU=RPU
	FROM PAGOS 
	WHERE NUMCREDITO=@NUMCREDITO
	GROUP BY RPU

	SELECT @CANTIDADREGISTROSSICOMOK=SUM(IMPORTE) 
	FROM REGISTROSSICOMOK RS WITH(NOLOCK) 	
	WHERE NUMCREDITO=@NUMCREDITO
	AND ISNULL(RS.ARCHIVO ,'') NOT IN ('CUENTARAP','PAGORAP','LIQUIDACIÓN EN VENTANILLA CFE (PAGO FUERA DE FACTURACIÓN)','NA - EXTRACTOR1','NA - EXTRACTOR2','NA - ARQUEO1','NA - ARQUEO2')
	AND RS.ESTATUS = '01'
	AND RS.ERROR = 0
	AND RS.PROCESADO = 1 
	--AND ISNULL(RS.PAGODEMAS,0) <> 1
	AND ISNULL(RS.PAGOELIMINADO,0) <> 1


	print 'credito: '+CONVERT(VARCHAR,@numcredito)+' en sirca: '+CONVERT(VARCHAR,@CANTIDADPAGOS)+'en registrossicomok: '+CONVERT(VARCHAR,@CANTIDADREGISTROSSICOMOK)


set @NUMCREDITO=NULL

SELECT TOP 1 @NUMCREDITO=L.NUMCREDITO
FROM LOGSPAPLICARARQUEO L
WHERE USUARIO= 'AMURO' AND FECHAEJECUCION > '2017-02-24 16:40:33.993'
AND CANTIDADPAGADAENARQUEO=CANTIDADENREGISTROSSICOMOK AND (SELECT SUM(IMPORTE) FROM PAGOS WHERE NUMCREDITO=L.NUMCREDITO) > CANTIDADENREGISTROSSICOMOK

END 