DECLARE 
@NUMCREDITO				AS VARCHAR(9),
@NUMPAGOS				AS INT

--INICIALIZO VARIABLES 
SET @NUMCREDITO =NULL
SET @NUMPAGOS = 0


IF OBJECT_ID('tempdb..#TMP') IS NOT NULL DROP TABLE #TMP

-- CREO TABLA TEMPORAL 
CREATE TABLE #TMP (NUMCREDITO [varchar](9) NULL ,NUMAMORT INT NULL, NUMPAGOS INT NULL, PROCESADO INT NULL )

-- INSERTO DATOS EN TABLA TEMPORAL 
INSERT INTO #TMP (NUMCREDITO,NUMAMORT, NUMPAGOS, PROCESADO)
SELECT TMP.NUMCREDITO AS NUMCREDITO, COUNT(*) AS NUMAMORT ,(SELECT COUNT(*) FROM DET_AMORTIZACION WHERE SOLICITUDSCC = TMP.NUMCREDITO) AS NUMPAGOS, NULL AS PROCESADO  
FROM DET_AMORTIZACION D 
JOIN (SELECT NUMCREDITO, PAGOFIJO, ULTIMAAMORTIZACION
FROM CREDITOS
WHERE ESTATUSCREDITO IN ('7','6')) AS TMP ON TMP.NUMCREDITO = D.SOLICITUDSCC AND D.SALDO NOT IN (TMP.PAGOFIJO) AND D.SALDO NOT IN (TMP.ULTIMAAMORTIZACION)
WHERE ESTATUS NOT IN ('14') AND PAGARE NOT IN ('25','49')
GROUP BY TMP.NUMCREDITO
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC


SELECT *
FROM #TMP


SELECT TOP 1 @NUMCREDITO=NUMCREDITO, @NUMPAGOS = NUMPAGOS
FROM #TMP 
WHERE PROCESADO IS NULL 


WHILE @NUMCREDITO IS NOT NULL
BEGIN
	-- SI TIENE 25 O 49 AMORTIZACIONES CORRO SP dbo.FIDEArreglaPagosConIVA DE LO CONTRARIO dbo.FIDEArreglaPagos
	IF @NUMPAGOS = 25 OR @NUMPAGOS = 49
	BEGIN 
	 PRINT 'PROCESANDO FIDEArreglaPagosConIVA AL CREDITO : ' + @NUMCREDITO
	 EXEC dbo.FIDEArreglaPagosConIVA @NUMCREDITO
	END 
	ELSE
	BEGIN
		PRINT 'PROCESANDO FIDEArreglaPagos AL CREDITO : ' + @NUMCREDITO
		EXEC dbo.FIDEArreglaPagos @NUMCREDITO
	END
	-- ACTUALIZO EL NUMERO DE CREDITO PARA 
	
	UPDATE #TMP 
	SET PROCESADO = 1 
	WHERE NUMCREDITO = @NUMCREDITO


	--INICIALIZO VARIABLES 
	SET @NUMCREDITO =NULL
	SET @NUMPAGOS = 0


	SELECT TOP 1 @NUMCREDITO=NUMCREDITO, @NUMPAGOS = NUMPAGOS
	FROM #TMP 
	WHERE PROCESADO IS NULL 

END


IF OBJECT_ID('tempdb..#TMP') IS NOT NULL DROP TABLE #TMP

