DECLARE 
 @RPU				VARCHAR(12)    
,@NUMCREDITO		NUMERIC(10,0)    
,@NUMCREDITOBANDERA	NUMERIC(10,0)   
,@REFERENCIA		VARCHAR(17)    
,@IMPORTE			NUMERIC(8,2)    
,@PAGARE			INT    
,@TIPOPAGO			VARCHAR(2)    
,@FECHAEE			VARCHAR(12)
,@ID_EDOCUENTA		INT 
,@IDCCONCEPTO		INT 
,@LINEACONCEPTO		VARCHAR(255)
,@PROCESADO			INT
,@TEXTOPROCESO		VARCHAR(100)
,@STATUSANTERIOR	VARCHAR(100)
,@STATUSFINAL		VARCHAR(100)
,@RESPUESTASTORED	VARCHAR(100)
,@TIPOCONVENIO		INT
,@ESTADOLIQUIDACION	INT
,@IDMANUAL			INT
,@MESFACT			VARCHAR(2)
,@YFACT				VARCHAR(2)
,@USER				VARCHAR(100)

-- INICIALIZO VARIABLES 

SET @RPU = NULL
SET @NUMCREDITO = NULL 
SET @NUMCREDITOBANDERA = NULL 
SET @REFERENCIA = NULL
SET @IMPORTE = NULL
SET @PAGARE = NULL
SET @TIPOPAGO = NULL
SET @FECHAEE = NULL
SET @ID_EDOCUENTA = NULL
SET @IDCCONCEPTO = NULL
SET @LINEACONCEPTO = NULL
SET @PROCESADO	 = 0
SET @ESTADOLIQUIDACION = 0
SET @TIPOCONVENIO= 0
SET @STATUSANTERIOR = NULL 
SET @STATUSFINAL = NULL
SET @RESPUESTASTORED = NULL
SET @MESFACT = NULL
SET @YFACT= NULL
SET @USER =NULL

-- SE OBTIENE LA PRIMERA REFERENCIA A PROCESAR 

SELECT TOP 1
	   @ID_EDOCUENTA = C.IDEDOCUENTA_MOV,
	   @IDCCONCEPTO = C.ID,
	   @NUMCREDITO=LEFT(RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17), 9),
	   @REFERENCIA= RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17),
	   @LINEACONCEPTO = C.CCONCEPTO,
	   @IMPORTE = M.IMPORTE,
	   @FECHAEE = M.FECHAOPERACION
FROM DBO.EDOCUENTA_CCONCEPTO C
JOIN DBO.EDOCUENTA_MOV M ON M.ID = C.IDEDOCUENTA_MOV
WHERE  C.CCONCEPTO LIKE '%PAGO DETALLE%' AND C.ESTATUS='PENDIENTE'

IF @NUMCREDITO IS NULL
BEGIN
	PRINT 'NO SE ENCONTRO NINGUNA REFERENCIA PARA PROCESAR'
END



WHILE @NUMCREDITO IS NOT NULL 
BEGIN
	PRINT 'PROCESANDO REFERENCIA: ' + @REFERENCIA
	
	-- VERIFICAMOS QUE NO FUE PROCESADO CON ANTERIORIDAD 
	   SELECT TOP 1
	   @STATUSANTERIOR = C.ESTATUS
	   FROM DBO.EDOCUENTA_CCONCEPTO C
	   JOIN DBO.EDOCUENTA_MOV M ON M.ID = C.IDEDOCUENTA_MOV
	   WHERE  C.CCONCEPTO LIKE '%PAGO DETALLE%' AND C.ESTATUS NOT IN ('PENDIENTE') AND M.IMPORTE = @IMPORTE AND  M.FECHAOPERACION = @FECHAEE 
	   AND  RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17) = @REFERENCIA
	   PRINT 'VERIFICANDO SI ES UNA REFERENCIA YA PROCESADA '
	IF @STATUSANTERIOR IS NOT NULL 
	BEGIN 
		-- UPDATEAMOS TODOS LOS REGISTROS IGUALES 
		UPDATE C
		SET ESTATUS=@STATUSANTERIOR
		FROM DBO.EDOCUENTA_CCONCEPTO C
		JOIN DBO.EDOCUENTA_MOV M ON M.ID = C.IDEDOCUENTA_MOV
		WHERE  C.CCONCEPTO LIKE '%PAGO DETALLE%' 
			AND C.ESTATUS IN ('PENDIENTE') 
			AND M.IMPORTE = @IMPORTE 
			AND M.FECHAOPERACION = @FECHAEE 
			AND RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17) = @REFERENCIA
		
		-- INICIALIZO VARIABLES 


			SET @RPU = NULL
			SET @NUMCREDITO = NULL 
			SET @NUMCREDITOBANDERA = NULL 
			SET @REFERENCIA = NULL
			SET @IMPORTE = NULL
			SET @PAGARE = NULL
			SET @TIPOPAGO = NULL
			SET @FECHAEE = NULL
			SET @ID_EDOCUENTA = NULL
			SET @IDCCONCEPTO = NULL
			SET @LINEACONCEPTO = NULL
			SET @PROCESADO	 = 0
			SET @ESTADOLIQUIDACION = 0
			SET @TIPOCONVENIO= 0
			SET @STATUSANTERIOR = NULL 
			SET @STATUSFINAL = NULL
			SET @RESPUESTASTORED = NULL
			SET @MESFACT = NULL
			SET @YFACT= NULL
			SET @USER =NULL
	END
-- SE VERIFICA SI ES LIQUIDACION ANTICIPADA
	PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UNA LIQUIDACION ANTICIPADA '
	SELECT TOP 1 @NUMCREDITOBANDERA=NUMCREDITO , @ESTADOLIQUIDACION = ESTADO
	FROM SOLICITUDPAGOANTICIPADO
	WHERE  NUMCREDITO=@NUMCREDITO AND MONTOPAGAR = @IMPORTE

	IF  @NUMCREDITOBANDERA IS NOT NULL 
	BEGIN
	-- EJECUTAMOS STORED DE APLICACION DE LIQUIDACIONES ANTICIPADAS 
		SELECT 1 
		EXEC SP_GRABABANCO @RPU, @NUMCREDITO, @IMPORTE, @FECHAEE
		SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (LA)'
	END
	ELSE 
	BEGIN 
		-- VERIFICO SI ES CONVENIO 
		PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UN  CONVENIO '
		SELECT TOP 1 @NUMCREDITOBANDERA=CON.CREDITO , @TIPOCONVENIO = CON.TIPOCONVENIO
		FROM CONVENIOS CON 
		WHERE  CON.CREDITO=@NUMCREDITO AND (CON.REFERENCIA=@REFERENCIA OR CON.REFERPARCIALIDAD = @REFERENCIA )
	
		IF @NUMCREDITOBANDERA IS NOT NULL 
		BEGIN
		-- TRAEMOS DATOS NECESARIOS PARA PROCESAR CONVENIO
				SELECT 
				TOP 1
				@RPU=CON.RPU, 
				@PAGARE = DET.PAGARE,
				@TIPOPAGO = CASE WHEN DET.PAGARE > 0 THEN 'P' ELSE 'A' END
				FROM EDOCUENTA_MOV E
				JOIN EDOCUENTA_CCONCEPTO C ON C.IDEDOCUENTA_MOV=E.ID
				JOIN CONVENIOS CON ON CON.CREDITO= LEFT(RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17), 9) AND (CON.REFERENCIA=RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17) OR CON.REFERPARCIALIDAD = RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17))
				JOIN DET_CONVENIO DET ON DET.CREDITO = CON.CREDITO AND DET.RPU = CON.RPU 
				WHERE RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17)=@REFERENCIA AND DET.ESTATUS NOT IN ('14')
				ORDER BY FECHA ASC
		-- DE ACUERDO AL TIPO DE CONVENIO SE APLICA EL STORED CORRECTO 
			IF @TIPOCONVENIO = 5 
			BEGIN
				PRINT 'PROCESANDO CONVENIO TIPO 5 CON NUMCREDITO = ' + CONVERT(VARCHAR,@NUMCREDITO)
				EXEC SP_CAPTURAPAGOCONVENIO_ESPECIAL @RPU, @NUMCREDITO , @REFERENCIA , @IMPORTE  , @PAGARE , @TIPOPAGO , @FECHAEE 
			END 
			ELSE 
			BEGIN 
			PRINT 'PROCESANDO CONVENIO TIPO ' + CONVERT(VARCHAR,@TIPOCONVENIO) + ' CON NUMCREDITO = ' + CONVERT(VARCHAR,@NUMCREDITO)
				EXEC SP_CAPTURAPAGOCONVENIO @RPU, @NUMCREDITO , @REFERENCIA , @IMPORTE  , @PAGARE , @TIPOPAGO , @FECHAEE 
			END 
			PRINT @RPU 
			PRINT @NUMCREDITO 
			PRINT @REFERENCIA 
			PRINT @IMPORTE  
			PRINT @PAGARE 
			PRINT @TIPOPAGO 
			PRINT @FECHAEE 
			SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (CONVENIO)'
		END
		ELSE 
		BEGIN 
			-- SE DEBERA BUSCA EN LA TABLA DE REFERENCIAS MANUALES DE CLAUDIA  
			PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UNA REFERENCIA MANUAL '
			SELECT @NUMCREDITOBANDERA = NUMCREDITO, @IDMANUAL = ID
			FROM EDOCUENTA_REF
			WHERE NUMCREDITO=@NUMCREDITO AND IMPORTE = @IMPORTE
			IF @NUMCREDITOBANDERA IS NOT NULL 
			BEGIN
				SET @MESFACT = SUBSTRING(@FECHAEE, 4, 2)
				SET @YFACT= SUBSTRING(@FECHAEE, 0, 4)
				SELECT  @USER = suser_sname()
				
				EXEC [nsp_Insert_PagoSIRCA] @NUMCREDITO, @FECHAEE, @FECHAEE, @FECHAEE, @IMPORTE, @YFACT ,@MESFACT, '96', '12', 'CUENTARAP' , @USER																			
				SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (MANUAL)'	
			END 
			ELSE 
			BEGIN 
				SELECT 1
				SET @STATUSFINAL = 'NO SE PUDO PROCESAR LA REFERENCIA ' 
			END
		END
	END
	-- SE COLORCA UNA MARCA DE PROCESADO O DE ERROR SEGUN SEA EL CASO
	IF @NUMCREDITO IS NOT NULL AND @STATUSFINAL IS NOT NULL
	BEGIN
		UPDATE C
		SET ESTATUS=@STATUSFINAL
		FROM DBO.EDOCUENTA_CCONCEPTO C
		JOIN DBO.EDOCUENTA_MOV M ON M.ID = C.IDEDOCUENTA_MOV
		WHERE  C.CCONCEPTO LIKE '%PAGO DETALLE%' 
			AND C.ESTATUS IN ('PENDIENTE') 
			AND M.IMPORTE = @IMPORTE 
			AND M.FECHAOPERACION = @FECHAEE 
			AND RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17) = @REFERENCIA
	END


	--REINICIAMOS VARIABLES 

		SET @RPU = NULL
		SET @NUMCREDITO = NULL 
		SET @NUMCREDITOBANDERA = NULL 
		SET @REFERENCIA = NULL
		SET @IMPORTE = NULL
		SET @PAGARE = NULL
		SET @TIPOPAGO = NULL
		SET @FECHAEE = NULL
		SET @ID_EDOCUENTA = NULL
		SET @IDCCONCEPTO = NULL
		SET @LINEACONCEPTO = NULL
		SET @PROCESADO	 = 0
		SET @ESTADOLIQUIDACION = 0
		SET @TIPOCONVENIO= 0
		SET @STATUSANTERIOR = NULL 
		SET @STATUSFINAL = NULL
		SET @RESPUESTASTORED = NULL
		SET @MESFACT = NULL
		SET @YFACT= NULL
		SET @USER =NULL

-- SE OBTIENE LA SIGUIENTE  REFERENCIA A PROCESAR 

	SELECT TOP 1
		   @ID_EDOCUENTA = C.IDEDOCUENTA_MOV,
		   @IDCCONCEPTO = C.ID,
		   @NUMCREDITO=LEFT(RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17), 9),
		   @REFERENCIA= RIGHT(LTRIM(RTRIM(C.CCONCEPTO)), 17),
		   @LINEACONCEPTO = C.CCONCEPTO,
		   @IMPORTE = M.IMPORTE,
		   @FECHAEE = M.FECHAOPERACION
	FROM DBO.EDOCUENTA_CCONCEPTO C
    JOIN DBO.EDOCUENTA_MOV M ON M.ID = C.IDEDOCUENTA_MOV
	WHERE  C.CCONCEPTO LIKE '%PAGO DETALLE%' AND C.ESTATUS='PENDIENTE'
END
PRINT 'SE HA TERMINADO LA EJECUCION DEL PROCESO'
