DECLARE 
 @RPU					VARCHAR(12)    
,@NUMCREDITO			NUMERIC(10,0)    
,@NUMCREDITOBANDERA		NUMERIC(10,0)   
,@NUMCREDITOBANDERA2	NUMERIC(10,0) 
,@REFERENCIA			VARCHAR(17)    
,@IMPORTE				NUMERIC(8,2)    
,@PAGARE				INT    
,@TIPOPAGO				VARCHAR(2)    
,@FECHAEE				VARCHAR(12)
,@ID_EDOCUENTA			INT 
,@IDCCONCEPTO			INT 
,@LINEACONCEPTO			VARCHAR(255)
,@PROCESADO				INT
,@TEXTOPROCESO			VARCHAR(100)
,@STATUSANTERIOR		VARCHAR(100)
,@STATUSFINAL			VARCHAR(100)
,@RESPUESTASTORED		VARCHAR(100)
,@TIPOCONVENIO			INT
,@ESTADOLIQUIDACION		INT
,@IDMANUAL				INT
,@MESFACT				VARCHAR(2)
,@YFACT					VARCHAR(2)
,@YEAR					VARCHAR(4)=NULL
,@USER					VARCHAR(100)
,@INDICE				VARCHAR(2)
,@RES					VARCHAR(MAX)= NULL
,@TEXT					VARCHAR(MAX)= NULL
,@ESCONVENIO			varchar(9) = NULL
,@SUMCONVENIO			NUMERIC(8,2) = 0
,@TIPO_CONVENIO			INT = 0
,@IMPORTECONV			NUMERIC(8,2)
-- DROP TABLE #t
-- INICIALIZO VARIABLES 

SET @RPU = NULL
SET @NUMCREDITO = NULL 
SET @NUMCREDITOBANDERA = NULL 
SET @NUMCREDITOBANDERA2 = NULL 
SET @REFERENCIA = NULL
SET @IMPORTE = NULL
SET @PAGARE = NULL
SET @TIPOPAGO = NULL
SET @FECHAEE = NULL
SET @ID_EDOCUENTA = NULL
SET @IDCCONCEPTO = NULL
SET @LINEACONCEPTO = NULL
SET @PROCESADO	 = 0
SET @ESTADOLIQUIDACION = 0
SET @TIPOCONVENIO= 0
SET @STATUSANTERIOR = NULL 
SET @STATUSFINAL = NULL
SET @RESPUESTASTORED = NULL
SET @MESFACT = NULL
SET @YFACT= NULL
SET @USER =NULL
SET @INDICE = NULL
SET @YEAR =NULL
SET @RES = NULL 

-- SE OBTIENE LA PRIMERA REFERENCIA A PROCESAR 

SELECT TOP 1
	@NUMCREDITO=LEFT(RIGHT(LTRIM(RTRIM(REFERENCIAMOV)), 17), 9),
	@REFERENCIA= RIGHT(LTRIM(RTRIM(REFERENCIAMOV)), 17),
	@IMPORTE = IMPORTEMOV,
	@FECHAEE = convert(varchar,FechaMov,112)  
FROM SIRCANAC.DBO.EDOCUENTA_HSBC 
WHERE TIPOARCHIVO = 'RPTMOVDIARIO'
AND ESTATUS IN ('Pendiente')
AND DESCRIPCION LIKE 'ABONO%'

IF @NUMCREDITO IS NULL
BEGIN
	PRINT 'NO SE ENCONTRO NINGUNA REFERENCIA PARA PROCESAR'
END

-- declaro tabla temporal para guardar resultados de storeds 
		IF OBJECT_ID('tempdb..#t') IS NOT NULL
		BEGIN
			DROP TABLE #t
		END
		ELSE 
		BEGIN
			create table  #t ( indice int, resultado VARCHAR(MAX) )
		END


WHILE @NUMCREDITO IS NOT NULL 
BEGIN
	PRINT 'PROCESANDO REFERENCIA: ' + @REFERENCIA
	
-- SE VERIFICA SI ES LIQUIDACION ANTICIPADA
	PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UNA LIQUIDACION ANTICIPADA '
	SELECT TOP 1 @NUMCREDITOBANDERA=NUMCREDITO , @ESTADOLIQUIDACION = ESTADO
	FROM SOLICITUDPAGOANTICIPADO
	WHERE  NUMCREDITO=@NUMCREDITO AND MONTOPAGAR = @IMPORTE AND estado = 0
	IF  @NUMCREDITOBANDERA IS NOT NULL 
	BEGIN
	-- OBTENGO EL RPU DEL CREDITO
	SELECT TOP 1 @RPU = RPU FROM creditos WHERE NumCredito=@NUMCREDITO
	
	-- EJECUTAMOS STORED DE APLICACION DE LIQUIDACIONES ANTICIPADAS 
		PRINT 'SE ESTA PROCESANDO LA (LA) CON LOS SIGUIENTES DATOS: '
		PRINT @RPU
		PRINT @NUMCREDITO
		PRINT @IMPORTE
		PRINT @FECHAEE
		
		--CREO UNA TABLA TEMPORAL PARA CACHAR EL RESULTADO DEL STORED

		INSERT INTO #t (indice,resultado)
		EXEC SP_GRABABANCO @RPU, @NUMCREDITO, @IMPORTE, @FECHAEE 
		--ASIGNANDO EL VALOR DE LA COLUMNA A LA VARIABLE.
		SELECT @INDICE = indice, @res=resultado FROM #t
		SET @STATUSFINAL = @STATUSFINAL + @res
		truncate table #t
		IF @INDICE = 1 
		BEGIN
			SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (LA) '
		END
		ELSE 
		BEGIN
			SET @STATUSFINAL = 'EL PAGO FALLO (LA) '
		END
		SET @STATUSFINAL = @STATUSFINAL + @res
		truncate table #t
	END
	ELSE 
	BEGIN 
		-- VERIFICO SI ES CONVENIO 
		PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UN  CONVENIO '
		SELECT TOP 1 @NUMCREDITOBANDERA=CON.CREDITO , @TIPOCONVENIO = CON.TIPOCONVENIO
		FROM CONVENIOS CON 
		WHERE  CON.CREDITO=@NUMCREDITO AND (CON.REFERENCIA=@REFERENCIA OR CON.REFERPARCIALIDAD = @REFERENCIA )
		
	
	
		IF @NUMCREDITOBANDERA IS NOT NULL 
		BEGIN
		-- TRAEMOS DATOS NECESARIOS PARA PROCESAR CONVENIO
				SELECT 
				TOP 1
					@RPU=CON.RPU, 
					@PAGARE = DET.PAGARE,
					@TIPOPAGO = CASE WHEN DET.PAGARE > 0 THEN 'P' ELSE 'A' END
				FROM SircaNac.dbo.EdoCuenta_HSBC E
				JOIN CONVENIOS CON ON CON.CREDITO= LEFT(RIGHT(LTRIM(RTRIM(E.ReferenciaMov)), 17), 9) AND (CON.REFERENCIA=RIGHT(LTRIM(RTRIM(E.ReferenciaMov)), 17) OR CON.REFERPARCIALIDAD = RIGHT(LTRIM(RTRIM(E.ReferenciaMov)), 17))
				JOIN DET_CONVENIO DET ON DET.CREDITO = CON.CREDITO AND DET.RPU = CON.RPU 
				WHERE E.ReferenciaMov=@REFERENCIA AND DET.ESTATUS NOT IN ('14')
				ORDER BY FECHA ASC

				PRINT 'PREPARANDOSE A PROCESAR CONVENIO '	
				PRINT @RPU 
				PRINT @NUMCREDITO 
				PRINT @REFERENCIA 
				PRINT @IMPORTE  
				PRINT @PAGARE 
				PRINT @TIPOPAGO 
				PRINT @FECHAEE 
				
		-- DE ACUERDO AL TIPO DE CONVENIO SE APLICA EL STORED CORRECTO 
			IF @TIPOCONVENIO = 5 
			BEGIN
				PRINT 'PROCESANDO CONVENIO TIPO 5 CON NUMCREDITO = ' + CONVERT(VARCHAR,@NUMCREDITO)
				--CREO UNA TABLA TEMPORAL PARA CACHAR EL RESULTADO DEL STORED
				INSERT INTO #t 
				EXEC SP_CAPTURAPAGOCONVENIO_ESPECIAL @RPU, @NUMCREDITO , @REFERENCIA , @IMPORTE  , @PAGARE , @TIPOPAGO , @FECHAEE 
				SELECT top 1  @INDICE= indice, @res=resultado FROM #t
				IF @INDICE = 1 
				BEGIN
					SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (CONVENIO ESPECIAL) '
				END
				ELSE 
				BEGIN
					SET @STATUSFINAL = 'EL PAGO FALLO! (CONVENIO ESPECIAL) '
				END
				SET @STATUSFINAL = @STATUSFINAL + @res
				truncate table #t
			END 
			ELSE 
			BEGIN 
			PRINT 'PROCESANDO CONVENIO TIPO ' + CONVERT(VARCHAR,@TIPOCONVENIO) + ' CON NUMCREDITO = ' + CONVERT(VARCHAR,@NUMCREDITO)	
				INSERT INTO #t 
				EXEC SP_CAPTURAPAGOCONVENIO @RPU, @NUMCREDITO , @REFERENCIA , @IMPORTE  , @PAGARE , @TIPOPAGO , @FECHAEE 
				SELECT top 1 @INDICE= indice, @res=resultado FROM #t
				IF @INDICE = 1 
				BEGIN
					SET @STATUSFINAL = 'SE PROCESO CORRECTAMENTE (CONVENIO ESPECIAL) '
				END
				ELSE 
				BEGIN
					SET @STATUSFINAL = 'EL PAGO FALLO! (CONVENIO ESPECIAL) '
				END
				SET @STATUSFINAL = @STATUSFINAL + @res
				truncate table #t
				
			END 
		END
		ELSE 
		BEGIN 
			-- SE DEBERA BUSCA EN LA TABLA DE REFERENCIAS MANUALES DE CLAUDIA  
			PRINT 'VERIFICANDO SI LA REFERENCIA '+@REFERENCIA+' ES UNA REFERENCIA MANUAL '
			SELECT @NUMCREDITOBANDERA = NUMCREDITO, @IDMANUAL = ID, @ESCONVENIO = idConvenio
			FROM EDOCUENTA_REF
			WHERE NUMCREDITO=@NUMCREDITO AND IMPORTE = @IMPORTE
			IF @NUMCREDITOBANDERA IS NOT NULL 
			BEGIN
				PRINT 'PREPARANDOSE A PROCESAR PAGO MANUAL '	
				PRINT @NUMCREDITO 
				PRINT @REFERENCIA 
				PRINT @IMPORTE   
				PRINT @FECHAEE 
				SET @MESFACT = substring(ltrim(rtrim(@FECHAEE)),5,2)
				SET @YEAR= substring(ltrim(rtrim(@FECHAEE)),1,4)
				SELECT  @USER = suser_sname()
				print @MESFACT
				PRINT @YEAR
				print @USER

				EXEC	@INDICE = [dbo].[nsp_Insert_PagoSIRCA]
						@NumeroCredito = @NUMCREDITO,
						@FechaPago = @FECHAEE,
						@FechaFac = @FECHAEE,
						@FechaVenci = @FECHAEE,
						@Importe = @IMPORTE,
						@AnioFact = @YEAR,
						@MesFact = @MESFACT,
						@Estatus = 96,
						@TipoPago = 12,
						@Archivo = N'CUENTARAP',
						@Usuario = @USER,
						@LogSQL = @RES OUTPUT
				
				INSERT INTO #T (INDICE,RESULTADO)
				SELECT	@INDICE, @RES 
				SELECT @INDICE = INDICE, @RES=RESULTADO FROM #T
				SET @STATUSFINAL = '(PAGO MANUAL PROCESADO )'
				PRINT 'RES ES : '+ CONVERT(VARCHAR(100),ISNULL(@RES,''))
				SET @STATUSFINAL = @STATUSFINAL + ISNULL(@RES,' ')
				TRUNCATE TABLE #T
				SET @RES = NULL 						
				-- SI ES UN CONVENIO APLICAMOS LOS PAGOS A DET_CONVENIO 
				IF @ESCONVENIO=0 BEGIN
					SET @ESCONVENIO=NULL
				END
				IF @ESCONVENIO IS NOT NULL
				BEGIN
				-- SE APLICA EL IMPORTE A DET_CONVENIO 
					PRINT 'ES UN CONVENIO Y SE PROCEDE A MATAR AMORTIZACIONES CORRESPONDIENTES'
					SELECT @SUMCONVENIO = SUM(IMPORTE)
					FROM det_convenio
					WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14') AND FOLIO = @ESCONVENIO
					SET @IMPORTECONV = @IMPORTE
					WHILE @SUMCONVENIO >=  @IMPORTECONV
					BEGIN 					
						PRINT 'SE MATA AMORTIZACION CON: FOLIO: '+convert(varchar,@ESCONVENIO)
						SELECT TOP  1 @IMPORTECONV=@IMPORTECONV-importe
						FROM det_convenio
						WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14') AND FOLIO = @ESCONVENIO 
						ORDER BY FECHA ASC
						UPDATE det_convenio
						SET ESTATUS = 14 , IMPORTEPAGO = IMPORTE, fechapago=@FECHAEE
						WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14') AND FOLIO = @ESCONVENIO AND FECHA IN (
							SELECT TOP  1 FECHA 
							FROM det_convenio
							WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14') AND FOLIO = @ESCONVENIO 
							ORDER BY FECHA ASC
						)
						SET @SUMCONVENIO = 0
						SELECT @SUMCONVENIO = SUM(IMPORTE)						
						FROM det_convenio
						WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14') AND FOLIO = @ESCONVENIO
					END
					SELECT @PAGARE=COUNT(*)					
					FROM det_convenio
					WHERE CREDITO=@NUMCREDITO AND ESTATUS NOT IN ('14')
			
					
					-- VERIFICO SI SE TERMINA CONVENIO 
					IF @PAGARE = 0
					BEGIN   
						PRINT ' COPIANDO EL CONVENIO A HISTORICO ...  '
						UPDATE CONVENIOS SET ESTATUS=3 WHERE CREDITO=@NUMCREDITO AND ESTATUS=2        
						UPDATE CREDITOS SET CONVENIO=0 WHERE NUMCREDITO=@NUMCREDITO    
				      
						INSERT INTO CONVENIOSHISTORICO (TIPOCONVENIO,FECHASOL,RPU,CREDITO,ESTATUS,ADEUDO,USUARIOSOL,REFERENCIA,FECHAVIGENCIA,CAPITAL,    
						INTERES,IVADEINTERES,MORATORIO,IVAMORATORIO,CARGOS,CAPITALXD,IVAXD,INTERESXD,SALDOINSOLUTOLA,ANTICIPO,FECHAULTIMOPAGO,    
						AMORCONVENIDA,NUMPAGOS, LUGAR,FOLIO,REFERPARCIALIDAD,CARGOVIGENTE,AMORTVENCIDAS,TOTALMORATORIO)    
						SELECT TIPOCONVENIO,FECHASOL,RPU,CREDITO,ESTATUS,ADEUDO,USUARIOSOL,REFERENCIA,FECHAVIGENCIA,CAPITAL,INTERES,IVADEINTERES,    
						MORATORIO,IVAMORATORIO,CARGOS,CAPITALXD,IVAXD,INTERESXD,SALDOINSOLUTOLA,ANTICIPO,FECHAULTIMOPAGO,AMORCONVENIDA,NUMPAGOS,    
						LUGAR,FOLIO,REFERPARCIALIDAD,CARGOVIGENTE,AMORTVENCIDAS,TOTALMORATORIO FROM CONVENIOS WHERE CREDITO = @NUMCREDITO    
				    
						INSERT INTO DET_CONVENIOHISTORICO(FOLIO,RPU,CREDITO,PAGARE,FECHA,IMPORTE,ESTATUS,IMPORTEPAGO,FECHAPAGO,ENVIOLYF,IDCARGADIARIAFECHARAP,CAPITALVENCIDO,INTERESVENCIDO,IVAINTERESVENCIDO,MORATORIO,IVAMORATORIO)    
						SELECT FOLIO,RPU,CREDITO,PAGARE,FECHA,IMPORTE,ESTATUS,IMPORTEPAGO,FECHAPAGO,ENVIOLYF,IDCARGADIARIAFECHARAP, CAPITALVENCIDO,INTERESVENCIDO,IVAINTERESVENCIDO,MORATORIO,IVAMORATORIO     
						FROM DET_CONVENIO WHERE CREDITO = @NUMCREDITO    
				      
						IF NOT EXISTS(SELECT * FROM CONVENIOS WHERE RPU=@RPU AND ESTATUS<3)    
							UPDATE CLIENTES SET BCONVENIO=0 WHERE RPU=@RPU    					
						
						SELECT @TIPO_CONVENIO = (SELECT TIPOCONVENIO FROM CONVENIOS WHERE CREDITO=@NUMCREDITO) 
						IF @TIPO_CONVENIO <> 1
						BEGIN 
							DELETE FROM CONVENIOS WHERE RPU=@RPU AND CREDITO = @NUMCREDITO  
							DELETE FROM DET_CONVENIO WHERE RPU=@RPU AND CREDITO = @NUMCREDITO    
						END   
					END 
					PRINT 'SE EJECUTA ARREGLAPAGOS AL CREDITO  '+convert(varchar,@NUMCREDITO)
					EXEC FIDEARREGLAPAGOS @NUMCREDITO
					-- TERMINA  VERIFICO SI SE TERMINA CONVENIO 					
				END								
			END 
			ELSE 
			BEGIN 
				SELECT 1
				SET @STATUSFINAL = 'NO SE PUDO PROCESAR LA REFERENCIA ' 
			END
		END
	END
	
	PRINT 'SALVANDO LOG DEL CREDITO '
	PRINT @NUMCREDITO
	PRINT 'CON EL ESTATUS FINAL '
	PRINT @STATUSFINAL
	
	-- SE COLORCA UNA MARCA DE PROCESADO O DE ERROR SEGUN SEA EL CASO
	IF @NUMCREDITO IS NOT NULL AND @STATUSFINAL IS NOT NULL
	BEGIN
		PRINT 'SE VA A UPDATEAR EL PAGO COMO :'+@STATUSFINAL
		UPDATE SIRCANAC.DBO.EDOCUENTA_HSBC 
		SET ESTATUS='PROCESADO'
		WHERE TIPOARCHIVO = 'RPTMOVDIARIO'
		AND ESTATUS NOT IN ('PROCESADO')
		AND REFERENCIAMOV = @REFERENCIA
		AND convert(varchar,FechaMov,112) = @FECHAEE
		AND DESCRIPCION LIKE 'ABONO%'
		
	END

		-- INICIALIZO VARIABLES 

		SET @RPU = NULL
		SET @NUMCREDITO = NULL 
		SET @NUMCREDITOBANDERA = NULL 
		SET @NUMCREDITOBANDERA2 = NULL 
		SET @REFERENCIA = NULL
		SET @IMPORTE = NULL
		SET @PAGARE = NULL
		SET @TIPOPAGO = NULL
		SET @FECHAEE = NULL
		SET @ID_EDOCUENTA = NULL
		SET @IDCCONCEPTO = NULL
		SET @LINEACONCEPTO = NULL
		SET @PROCESADO	 = 0
		SET @ESTADOLIQUIDACION = 0
		SET @TIPOCONVENIO= 0
		SET @STATUSANTERIOR = NULL 
		SET @STATUSFINAL = NULL
		SET @RESPUESTASTORED = NULL
		SET @MESFACT = NULL
		SET @YFACT= NULL
		SET @USER =NULL
		SET @INDICE = NULL
		SET @YEAR =NULL
		SET @RES = NULL 
		SET @ESCONVENIO = NULL
		SET @TIPO_CONVENIO = NULL

-- SE OBTIENE LA SIGUIENTE  REFERENCIA A PROCESAR 

		SELECT TOP 1
			@NUMCREDITO=LEFT(RIGHT(LTRIM(RTRIM(REFERENCIAMOV)), 17), 9),
			@REFERENCIA= RIGHT(LTRIM(RTRIM(REFERENCIAMOV)), 17),
			@IMPORTE = IMPORTEMOV,
			@FECHAEE = CONVERT(VARCHAR,FECHAMOV,112)  
		FROM SIRCANAC.DBO.EDOCUENTA_HSBC 
		WHERE TIPOARCHIVO = 'RPTMOVDIARIO'
		AND ESTATUS NOT AND ESTATUS IN ('Pendiente')
		AND DESCRIPCION LIKE 'ABONO%'
END
		IF OBJECT_ID('tempdb..#t') IS NOT NULL
		BEGIN
			DROP TABLE #t
		END
		COMMIT
		COMMIT
PRINT 'SE HA TERMINADO LA EJECUCION DEL PROCESO'
